spring:
  application:
    name: MedicineNotes

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.jdbc.core: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    org.springframework.orm.jpa: DEBUG
    com.zaxxer.hikari: DEBUG

jwt:
  lifetime: 3600000
  secret: testfkwofnasjfnueh83nd8274hf8efnw8eufnc8j4w9ncfh987sh84hn8c5h998aewhnf8choeg

limits:
  max-templates: 15
  max-duration: 90
  max-times-a-day: 18