spring:
  application:
    name: MedicineNotes
  datasource:
    url: jdbc:postgresql://localhost:5433/MedicineNotes
    username: admin
    password: secret

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.jdbc.core: DEBUG
    org.springframework.transaction: DEBUG

jwt:
  lifetime: 3600000
  secret: testfkwofnasjfnueh83nd8274hf8efnw8eufnc8j4w9ncfh987sh84hn8c5h998aewhnf8choeg

limits:
  max-templates: 15
  max-duration: 90
  max-times-a-day: 18